<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>ConfigurationManagerInputFix</AssemblyName>
    <RootNamespace>ConfigurationManagerInputFix</RootNamespace>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <TarkovDir Condition=" '$(TarkovDir)' == '' ">$(SolutionDir)..\..\</TarkovDir>
    <TarkovManagedDir>$(TarkovDir)EscapeFromTarkov_Data\Managed\</TarkovManagedDir>
    <TarkovBepInExCoreDir>$(TarkovDir)BepInEx\core\</TarkovBepInExCoreDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(TarkovBepInExCoreDir)0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(TarkovBepInExCoreDir)BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(TarkovManagedDir)UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(TarkovManagedDir)UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <!-- Gets the commit hash from git -->
  <Target Name="SetSourceRevisionId" BeforeTargets="InitializeSourceControlInformation">
    <Exec
      Command="git describe --long --always --dirty --exclude=* --abbrev=8"
      ConsoleToMSBuild="True"
      IgnoreExitCode="False"
    >
      <Output PropertyName="SourceRevisionId" TaskParameter="ConsoleOutput" />
    </Exec>
  </Target>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <OutputDLL Include="$(ProjectDir)$(OutDir)$(TargetName).dll" />
    </ItemGroup>

    <!-- Copies the output to the Tarkov game folder -->
    <Copy
      SourceFiles="@(OutputDLL);"
      DestinationFolder="$(TarkovDir)BepInEx\plugins\ConfigurationManagerInputFix\%(RecursiveDir)"
    />

    <!-- Creates a release zip file -->
    <RemoveDir Directories="$(ProjectDir)release" />
    <Copy
      SourceFiles="@(OutputDLL);"
      DestinationFolder="$(ProjectDir)release\ConfigurationManagerInputFix\BepInEx\plugins\ConfigurationManagerInputFix\%(RecursiveDir)"
    />
    <ZipDirectory
      SourceDirectory="$(ProjectDir)release\ConfigurationManagerInputFix\"
      DestinationFile="$(ProjectDir)release\ConfigurationManagerInputFix-$(ConfigurationName)-$(Version)-$(SourceRevisionId).zip"
    />
  </Target>
</Project>
